AWSTemplateFormatVersion: '2010-09-09'
Resources:
  lambda_datafoundry:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: encodedzipfile
        S3Key: output.b64
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::759301331949:role/lambda_datafoundry-role-jonnnf8o
      Runtime: python3.8
      Timeout: 30
      Environment:
        Variables:
          API_URL: https://api.coingecko.com/api/v3/coins/markets
          S3_BUCKET_NAME: datafoundry.adilashfaq
          REGION: ap-southeast-2
      MemorySize: 128
      Policies:
        - PolicyName: AWSEventsTriggerLambdaFunction
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AWSEvents_trigger-lambda-function_Id15048ffb-4fc0-4ee6-892d-79b857efa85b
                Effect: Allow
                Principal:
                  Service: events.amazonaws.com
                Action: lambda:InvokeFunction
                Resource: !Sub 'arn:aws:lambda:ap-southeast-2:759301331949:function:lambda_datafoundry'
                Condition:
                  ArnLike:
                    AWS:SourceArn: 'arn:aws:events:ap-southeast-2:759301331949:rule/trigger-lambda-function'
        - PolicyName: AWSLambdaBasicExecutionRole-f340bd9c-74e7-4401-ab2e-21c55b08955d
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: arn:aws:logs:ap-southeast-2:759301331949:*
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:ap-southeast-2:759301331949:log-group:/aws/lambda/lambda_datafoundry:*
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - s3-object-lambda:*
                Resource: '*'
    DependsOn: datafoundry.adilashfaq

  datafoundry.adilashfaq:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: datafoundry.adilashfaq
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: Rule1
            Status: Enabled
            ExpirationInDays: 365
      BucketPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub 'arn:aws:s3:::${datafoundry.adilashfaq}/coin-data.txt'

  MyEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: trigger-lambda-function
      Description: Trigger the Lambda function every minute
      ScheduleExpression: rate(1 minute)
      State: ENABLED
      Targets:
        - Arn: arn:aws:lambda:ap-southeast-2:759301331949:function:lambda_datafoundry
          Id: Id15048ffb-4fc0-4ee6-892d-79b857efa85b
      EventPattern:
        source:
          - aws.events
        detail-type:
          - Scheduled Event
        resources:
          - !Sub 'arn:aws:events:ap-southeast-2:759301331949:rule/trigger-lambda-function'

   
